server:
  port: 8085
feign:
  okhttp:
    enabled: true
# 用于nacos共享配置中的参数
hm:
  db:
    database: hm-trade
    host: localhost
    port: 3306
    user: root
    pw: root
  swagger:
    title: "黑马商城交易接口文档"
    package: com.hmall.trade.controller