server:
  port: 8084
feign:
  okhttp:
    enabled: true
# 用于nacos共享配置中的参数
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  db:
    database: hm-user
    host: localhost
    port: 3306
    user: root
    pw: root
  swagger:
    title: "黑马商城用户接口文档"
    package: com.hmall.user.controller