server:
  port: 8086
feign:
  okhttp:
    enabled: true
# 用于nacos共享配置中的参数
hm:
  db:
    database: hm-pay
    host: localhost
    port: 3306
    user: root
    pw: root
  swagger:
    title: "黑马商城支付接口文档"
    package: com.hmall.pay.controller