server:
  port: 8082
feign:
  okhttp:
    enabled: true
# 用于nacos共享配置中的参数
hm:
  db:
    database: hm-cart
    host: localhost
    port: 3306
    user: root
    pw: root
  swagger:
    title: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller