server:
  port: 8081
feign:
  okhttp:
    enabled: true
# 用于nacos共享配置中的参数
hm:
  db:
    database: hm-item
    host: localhost
    port: 3306
    user: root
    pw: root
  swagger:
    title: "黑马商城商品接口文档"
    package: com.hmall.item.controller